"""datapoint table

Revision ID: 3f5158ea9db8
Revises: 212a9493a158
Create Date: 2023-01-22 12:53:26.898387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5158ea9db8'
down_revision = '212a9493a158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('temperature')
        batch_op.drop_column('energy')
        batch_op.drop_column('precipitation')
        batch_op.drop_column('mood')
        batch_op.drop_column('pressure')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pressure', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('precipitation', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('energy', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
