"""datapoint table

Revision ID: 88a887b14840
Revises: ac673671c83b
Create Date: 2023-01-22 13:07:08.312014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a887b14840'
down_revision = 'ac673671c83b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('temperature')
        batch_op.drop_column('pressure')
        batch_op.drop_column('energy')
        batch_op.drop_column('mood')
        batch_op.drop_column('precipitation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precipitation', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('energy', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('pressure', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
