"""datapoint table

Revision ID: 92fe343b7dbf
Revises: 88a887b14840
Create Date: 2023-01-22 13:10:49.451469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92fe343b7dbf'
down_revision = '88a887b14840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_point')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mood')
        batch_op.drop_column('precipitation')
        batch_op.drop_column('pressure')
        batch_op.drop_column('energy')
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('energy', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('pressure', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('precipitation', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.VARCHAR(), nullable=True))

    op.create_table('data_point',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mood_value', sa.INTEGER(), nullable=False),
    sa.Column('energy_value', sa.INTEGER(), nullable=False),
    sa.Column('temperature', sa.FLOAT(), nullable=False),
    sa.Column('pressure', sa.FLOAT(), nullable=False),
    sa.Column('precipitation', sa.FLOAT(), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
