"""datapoint table

Revision ID: ac673671c83b
Revises: 3f5158ea9db8
Create Date: 2023-01-22 12:56:44.558299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac673671c83b'
down_revision = '3f5158ea9db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mood')
        batch_op.drop_column('energy')
        batch_op.drop_column('precipitation')
        batch_op.drop_column('pressure')
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('pressure', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('precipitation', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('energy', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
